name: ci

on:
  push:
    branches-ignore:
      - gh-pages
      - "renovate/**"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14]
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: cache
        with:
          path: ./node_modules
          key: node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

      - run: npm run lint

      - run: npm run build
