name: deploy

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "12"
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v2
        id: cache
        with:
          path: ./node_modules
          key: node-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

      - run: npm run build

      - run: |
          sudo apt-get install tree -y
          tree -H '.' -L 1 --noreport --charset utf-8 ./dist | tee dist/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: deploy ${{ github.ref }}
          force_orphan: true
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
